
font:
  normal:
    family: SauceCodePro Nerd Font Mono

window:
  title: Terminal

colors:

  primary:
    background: '#132029'
    forground:  '#AAAAAA'

  normal:
    black:    '#000000'
    red:      '#AA0000'
    green:    '#00AA00'
    yellow:   '#AA5500'
    blue:     '#0000AA'
    magenta:  '#AA00AA'
    cyan:     '#00AAAA'
    white:    '#AAAAAA'

  bright:
    black:    '#555555'
    red:      '#FF5555'
    green:    '#55FF55'
    yellow:   '#FFFF55'
    blue:     '#5555FF'
    magenta:  '#FF55FF'
    cyan:     '#55FFFF'
    white:    '#FFFFFF'
